import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { GradeBadge, RiskMeter, SeverityChip } from "@/components/mcp-audit/ui";
import { db } from "@/lib/db";
import { getDimension } from "@/lib/mcp-audit/taxonomy";
import type { Scorecard } from "@/lib/mcp-audit/types";

export const dynamic = "force-dynamic";

async function loadPublished(vendorId: string, slug: string) {
  const scan = await db.mcpAuditScan.findFirst({
    where: { publishSlug: slug, publishedVendorId: vendorId, published: true },
  });
  return scan;
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ vendorId: string; slug: string }>;
}): Promise<Metadata> {
  const { vendorId, slug } = await params;
  const scan = await loadPublished(vendorId, slug);
  if (!scan) return { title: "Audit — TrustMCP" };
  return {
    title: `${scan.name} — MCP audit`,
    description: `TrustMCP risk scorecard for ${scan.targetUrl} (grade ${scan.grade ?? "—"}).`,
  };
}

export default async function PublicAuditPage({
  params,
}: {
  params: Promise<{ vendorId: string; slug: string }>;
}) {
  const { vendorId, slug } = await params;
  const scan = await loadPublished(vendorId, slug);
  if (!scan || !scan.scorecard) notFound();
  const scorecard = scan.scorecard as unknown as Scorecard;
  const evidence = scan.evidence as { bundle?: { contentHash?: string } } | null;

  return (
    <div className="mx-auto max-w-3xl space-y-8 px-4 py-10">
      <header className="space-y-2">
        <Link href={`/trust/${vendorId}`} className="text-xs text-slate-400 hover:text-slate-600">
          ← Trust center
        </Link>
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <h1 className="text-3xl font-semibold">{scan.name}</h1>
            <div className="text-sm text-slate-500">{scan.targetUrl}</div>
            <div className="mt-1 text-xs text-slate-400">
              MCP audit · version {scan.publishedVersion} · scan schema {scorecard.schemaVersion}
            </div>
          </div>
          <GradeBadge grade={scorecard.grade} score={scorecard.overallScore} />
        </div>
        {scan.description && <p className="text-sm text-slate-600">{scan.description}</p>}
      </header>

      {scorecard.executiveSummary && (
        <section className="card">
          <h2 className="font-semibold">{scorecard.headline}</h2>
          <p className="mt-1 text-sm leading-relaxed text-slate-700">{scorecard.executiveSummary}</p>
          {scorecard.typicalUse && (
            <p className="mt-2 text-sm text-slate-600">
              <span className="font-medium">Typical use: </span>
              {scorecard.typicalUse}
            </p>
          )}
        </section>
      )}

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">Risk by dimension</h2>
        {scorecard.dimensions.map((d) => (
          <div key={d.dimension} className="card space-y-1">
            <div className="flex items-center justify-between">
              <span className="font-medium">{getDimension(d.dimension)?.name ?? d.dimension}</span>
              <div className="flex items-center gap-2">
                <SeverityChip severity={d.severity} />
                <span className="text-sm font-semibold">{d.score}</span>
              </div>
            </div>
            <RiskMeter score={d.score} />
            {d.summary && <p className="text-sm text-slate-600">{d.summary}</p>}
          </div>
        ))}
      </section>

      {scorecard.findings.length > 0 && (
        <section className="space-y-2">
          <h2 className="text-lg font-semibold">Findings</h2>
          {scorecard.findings.map((f) => (
            <div key={f.id} className="card">
              <div className="flex items-center gap-2">
                <SeverityChip severity={f.severity} />
                <span className="font-medium">{f.title}</span>
              </div>
              <p className="mt-1 text-sm text-slate-700">{f.detail}</p>
            </div>
          ))}
        </section>
      )}

      {evidence?.bundle?.contentHash && (
        <section className="card">
          <h3 className="font-semibold">Evidence</h3>
          <p className="text-sm text-slate-600">
            This scorecard is backed by a content-hashed evidence bundle of the server&apos;s tool
            contract and probe transcript.
          </p>
          <div className="mt-1 font-mono text-xs text-slate-500">sha256: {evidence.bundle.contentHash}</div>
        </section>
      )}

      <p className="text-xs text-slate-400">
        Generated by TrustMCP MCP Audit. A scorecard is a point-in-time assessment; verify against your
        own controls before integrating.
      </p>
    </div>
  );
}
