"""initial schema

Revision ID: 3eebbcdb41f3
Revises: 
Create Date: 2026-06-07 03:26:57.058472
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3eebbcdb41f3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('domains', sa.JSON(), nullable=False),
    sa.Column('branding', sa.JSON(), nullable=False),
    sa.Column('owner_token_hash', sa.String(), nullable=False),
    sa.Column('notify_email', sa.String(), nullable=True),
    sa.Column('notify_on_request', sa.Boolean(), nullable=False),
    sa.Column('listed', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_domains', sa.JSON(), nullable=False),
    sa.Column('auto_approve_crm', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_on_contract', sa.Boolean(), nullable=False),
    sa.Column('crm_provider', sa.String(), nullable=True),
    sa.Column('crm_token', sa.String(), nullable=True),
    sa.Column('crm_instance_url', sa.String(), nullable=True),
    sa.Column('agent_auto_approve', sa.Boolean(), nullable=False),
    sa.Column('nda_required', sa.Boolean(), nullable=False),
    sa.Column('nda_text', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('mark_status', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attestations_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('display_hint', sa.String(), nullable=False),
    sa.Column('requester_name', sa.String(), nullable=False),
    sa.Column('requester_domain', sa.String(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('artifact_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_keys_key_hash'), ['key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_keys_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('access', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('access_key_id', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('domain_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('challenge_token', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_verifications_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('key_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('requester_name', sa.String(), nullable=False),
    sa.Column('requester_domain', sa.String(), nullable=False),
    sa.Column('requester_contact', sa.String(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('access_key_id', sa.String(), nullable=True),
    sa.Column('auto_approved', sa.Boolean(), nullable=False),
    sa.Column('decision_reason', sa.String(), nullable=True),
    sa.Column('contract_storage_key', sa.String(), nullable=True),
    sa.Column('contract_sha256', sa.String(), nullable=True),
    sa.Column('nda_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nda_text_sha', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('key_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_key_requests_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('subprocessors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subprocessors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subprocessors_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('artifact_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_versions_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_versions_vendor_id'), ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_versions_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_versions_artifact_id'))

    op.drop_table('artifact_versions')
    with op.batch_alter_table('subprocessors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subprocessors_vendor_id'))

    op.drop_table('subprocessors')
    with op.batch_alter_table('key_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_key_requests_vendor_id'))

    op.drop_table('key_requests')
    with op.batch_alter_table('domain_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_verifications_vendor_id'))

    op.drop_table('domain_verifications')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_vendor_id'))

    op.drop_table('claims')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_vendor_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_vendor_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('access_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_keys_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_access_keys_key_hash'))

    op.drop_table('access_keys')
    op.drop_table('vendors')
    # ### end Alembic commands ###
